# Generated by Django 4.2.4 on 2023-10-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_alter_snippets_language_alter_snippets_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippets',
            old_name='lineous',
            new_name='linenos',
        ),
    ]
